# Generated by Django 2.2.14 on 2020-12-14 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(default='', max_length=20, verbose_name='Аббревиатура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='dates',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Dates', verbose_name='Важные даты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='tasks.Project', verbose_name='Проект'),
        ),
    ]
