# Generated by Django 2.2.14 on 2020-12-26 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201214_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='project',
            name='redline',
            field=models.DateTimeField(null=True, verbose_name='To be completed'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='redline',
            field=models.DateTimeField(null=True, verbose_name='To be completed'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Date name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Chief'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dates',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Dates', verbose_name='Important dates'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('pm', 'Project Manager'), ('dev', 'Developer'), ('qa', 'QA engineer'), ('analyst', 'Analyst'), ('area_dev', 'Dev Area Lead'), ('area_qa', 'QA Area Lead'), ('area_analyst', 'Analyst Area Lead'), ('lead_dev', 'Dev Lead'), ('lead_qa', 'QA Lead'), ('lead_analyst', 'Analyst Lead')], default='pm', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Not started'), ('in_progress', 'In progress'), ('delay', 'Delayed'), ('closed', 'Completed')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_end',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='date_start',
            field=models.DateField(verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('open', 'Not started'), ('in_progress', 'In progress'), ('delay', 'Delayed'), ('closed', 'Completed')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accept_criterion',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Acceptance Criterion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='tasks.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='redline',
            field=models.DateTimeField(null=True, verbose_name='To be completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='tasks.Sprint', verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('to-do', 'Not started'), ('in_progress', 'In progress'), ('postponed', 'Postponed'), ('done', 'Completed'), ('delay', 'Delayed'), ('late', 'Being late')], default='to-do', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_tasks',
            field=models.ManyToManyField(blank=True, related_name='parent_task', to='tasks.Task', verbose_name='Subtasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
