# Generated by Django 2.2.14 on 2020-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201226_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='redline',
            field=models.DateField(null=True, verbose_name='To be completed'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='redline',
            field=models.DateField(null=True, verbose_name='To be completed'),
        ),
    ]
